services:
  prodDB:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - prodDB:/var/lib/postgresql/data
    networks:
      - prodNetwork

  server:
    depends_on:
      prodDB:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST:-prodDB}
      - SERVER_HOST=${SERVER_HOST:-localhost}
      - SERVER_PORT=${SERVER_PORT:-4000}
      # Ne pas oublier de changer cette ligne quand la registration sera mise en place
      # - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:-abcdfzfefzefzefzeefghijkl}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:8000}
    image: kaitolight/2209-wns-adleman-citycompass-server
    networks:
      - prodNetwork
    healthcheck:
      test: 'curl --fail --request GET -H ''content-type:application/json'' --url ''http://localhost:4000/graphql?query=%7B__typename%7D'''
      interval: 5s
      timeout: 5s
      retries: 10

  client:
    image: kaitolight/2209-wns-adleman-citycompass-client
    networks:
      - prodNetwork
    volumes:
      - web-client-build:/app/build

  nginx:
    image: nginx:1.21.3 
    depends_on:
      client:
        condition: service_started
      server:
        condition: service_healthy
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
    networks:
      - prodNetwork

volumes:
  prodDB:
  web-client-build:

networks:
  prodNetwork:    
    

